package=libDatabase
version=git
targets=build,configure,deforaos-libdatabase.pc,download,extract,patch,sbom,sbominstall,tests
dist=Makefile,config.sh
config=sh

[metadata]
description=DeforaOS Database access library
copyright=(c) 2012-2026 The DeforaOS Project
license=BSD-2-Clause
homepage=https://git.defora.org/DeforaOS/libDatabase
download=https://ftp.defora.org/pub/DeforaOS/Apps/Database/src/libDatabase
maintainer=khorben
depends=deforaos-libsystem

#targets
#phony
[build]
type=script
script=../../../../System/src/script.sh
phony=1
depends=configure
install=

[configure]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=patch

[download]
type=script
script=../../../../System/src/script.sh
flags=-O URL=https://git.defora.org/DeforaOS/$(PACKAGE).git
phony=1
enabled=0

[extract]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=download

[patch]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=extract

[sbom]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=$(OBJDIR)deforaos-libdatabase.pc

[sbominstall]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=sbom

[tests]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=patch

#files
[deforaos-libdatabase.pc]
type=script
script=../script.sh
enabled=0
depends=project.conf
