package=libDesktop
version=git
targets=build,configure,deforaos-libdesktop.pc,download,extract,patch,sbom,sbominstall,tests
dist=Makefile,config.sh
config=sh

[metadata]
description=DeforaOS Desktop library
copyright=(c) 2009-2026 The DeforaOS Project
license=BSD-2-Clause
homepage=https://git.defora.org/DeforaOS/libDesktop
download=https://ftp.defora.org/pub/DeforaOS/Apps/Desktop/src/libDesktop/
maintainer=khorben
depends=deforaos-libsystem
#XXX does not work yet
#depends=deforaos-libsystem,gtk+-3.0

#targets
#phony
[build]
type=script
script=../../../../System/src/script.sh
phony=1
depends=configure
install=

[configure]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=patch

[download]
type=script
script=../../../../System/src/script.sh
flags=-O URL=https://git.defora.org/DeforaOS/$(PACKAGE).git
phony=1
enabled=0

[extract]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=download

[patch]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=extract

[sbom]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=$(OBJDIR)deforaos-libdesktop.pc

[sbominstall]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=sbom

[tests]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=patch

#files
[deforaos-libdesktop.pc]
type=script
script=../../../../System/src/script.sh
enabled=0
depends=project.conf
