package=strace
version=git
targets=build,configure,deforaos-strace.pc,download,extract,patch,sbom,sbominstall,tests
dist=Makefile,config.sh
config=sh

[metadata]
description=DeforaOS Devel strace
copyright=(c) 2004-2026 The DeforaOS Project
license=GPL-3.0-only
homepage=https://git.defora.org/DeforaOS/strace
download=https://ftp.defora.org/pub/DeforaOS/Apps/Devel/src/strace/
maintainer=khorben

#targets
#phony
[build]
type=script
script=../../../../System/src/script.sh
phony=1
depends=configure
install=

[configure]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=patch

[download]
type=script
script=../../../../System/src/script.sh
flags=-O URL=https://git.defora.org/DeforaOS/$(PACKAGE).git
phony=1
enabled=0

[extract]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=download

[patch]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=extract

[sbom]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=$(OBJDIR)deforaos-strace.pc

[sbominstall]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=sbom

[tests]
type=script
script=../../../../System/src/script.sh
phony=1
enabled=0
depends=patch

#files
[deforaos-strace.pc]
type=script
script=../../../../System/src/script.sh
enabled=0
depends=project.conf
