package=Splasher
version=git
targets=build,configure,deforaos-splasher.pc,download,extract,patch,sbom,sbominstall,tests
dist=Makefile,config.sh
config=sh

[metadata]
description=DeforaOS System Splasher
copyright=(c) 2010-2026 The DeforaOS Project
license=GPL-3.0-only
homepage=https://git.defora.org/DeforaOS/Splasher
download=https://ftp.defora.org/pub/DeforaOS/System/src/Splasher/
maintainer=khorben
depends=deforaos-libsystem,deforaos-libapp

#targets
#phony
[build]
type=script
script=../script.sh
phony=1
depends=configure
install=

[configure]
type=script
script=../script.sh
phony=1
depends=patch

[download]
type=script
script=../script.sh
flags=-O URL=https://git.defora.org/DeforaOS/$(PACKAGE).git
phony=1

[extract]
type=script
script=../script.sh
phony=1
depends=download

[patch]
type=script
script=../script.sh
phony=1
depends=extract

[sbom]
type=script
script=../script.sh
phony=1
enabled=0
depends=$(OBJDIR)deforaos-splasher.pc

[sbominstall]
type=script
script=../script.sh
phony=1
enabled=0
depends=sbom

[tests]
type=script
script=../script.sh
phony=1
enabled=0
depends=patch

#files
[deforaos-splasher.pc]
type=script
script=../script.sh
enabled=0
depends=project.conf
