name: DeforaOS C CI (ubuntu-latest)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  bootstrap:
    name: Bootstrap

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc make
    - name: bootstrap
      run: make bootstrap < /dev/null

  build:
    name: Complete build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          docbook-xsl \
          libevince-dev \
          libgtk-3-dev \
          libgtk-vnc-2.0-dev \
          libsofia-sip-ua-glib-dev \
          libxml2-utils \
          gcc \
          gtk-doc-tools \
          make
    - name: Bootstrap
      run: make bootstrap < /dev/null
    - name: Build
      run: |
        sudo chgrp -R $(id -g) /usr/local
        sudo chmod -R g+w /usr/local
        PATH="$PWD/tooldir-$(uname -s)-amd64/bin:$PATH" make install
